version: '3.3'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: saminda-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - saminda-network
    depends_on:
      - db

  # Nginx Web Server
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: saminda-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - saminda-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: saminda-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-saminda}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-saminda}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - saminda-db-data:/var/lib/mysql
    networks:
      - saminda-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  saminda-network:
    driver: bridge

volumes:
  saminda-db-data:
    driver: local