version: 2
updates:
  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/" # location of your composer.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "composer"

  # NPM/Yarn dependencies
  - package-ecosystem: "npm"
    directory: "/" # location of your package.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "npm"
